### ISSUE TITLE
qemu: speed up tests

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/go-qemu#101]
```
[zsh|matt@nerr-2]:~/src/github.com/digitalocean/go-qemu 0 (master) ± go test ./...
ok      github.com/digitalocean/go-qemu 4.004s
ok      github.com/digitalocean/go-qemu/hypervisor      0.002s
ok      github.com/digitalocean/go-qemu/internal/shellexec      0.002s
ok      github.com/digitalocean/go-qemu/internal/virsh  0.014s
ok      github.com/digitalocean/go-qemu/qmp     0.002s
```

Let's do what we can to make `qemu` tests as fast as the other packages; or at least, sub 1-second if possible.

**Comment by mdlayher** [comment]
Closed by #102 .

**Comment by ndedic** [comment]
I was about to say that tests are pretty fast for me (go-qemu 0.068s) only to realise that it's been resolved already. That was quick.

**Comment by mdlayher** [comment]
@ndedic Yep. :) Feel free to check out other issues though and let us know if something catches your eye.

We'd like to clean things up just a bit more and then do a real public announcement about the project to find more contributors and users.
