### ISSUE TITLE
qmp: consider deprecating LibvirtShellMonitor

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/go-qemu#132]
It got us started on this project, but at this point, I think that the RPC monitor is stable enough to totally replace the shell monitor when using libvirt.

Thoughts @digitalocean/go-qemu ?

**Comment by benlemasurier** [comment]
100% agree, my thoughts exactly.

**Comment by danderson** [comment]
My only thought is that LibvirtShellMonitor made it easy for me to get started, because it took exactly the same arguments as virsh, which I was familiar with already.

That said, that's maybe just an argument for a bit more documentation (e.g. "the libvirt unix domain socket is usually at /foo").

**Comment by benlemasurier** [comment]
I should add, my primary motivation for wanting to see the shell monitor deprecated is due to the fact that's it's also the most likely to fail. Under libvirt >= 1.3.2 and possibly earlier, we needed to patch `virsh` to always `fflush` on output.

**Comment by mdlayher** [comment]
I'd be okay with beefing up the documentation to make the RPC monitor more approachable too.

I guess there is no urgent need to yank it out, but if more issues like the one that @benlemasurier mentioned occur, I'd rather not have to tell users to patch their libvirt to use it, heh.

**Comment by danderson** [comment]
Yeah, makes sense to get rid of it.
