### ISSUE TITLE
qemu: consider moving to github.com/digitalocean/go-qemu/qemu

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/go-qemu#133]
For a long time, I didn't like the pattern I mentioned in the title.

Now, I find it pretty aggravating when repo and package names differ, because it's a surprise that you won't find out unless you explicitly check the code or docs.

Moving package `qemu` to a "subpackage" would also help clarify that this repository is a _collection_ of packages for interacting with QEMU.

On the other hand, right now, it's front and center, and the first thing users see. That's arguably something we want to preserve as well.

Thoughts?

**Comment by danderson** [comment]
+1 from me. Having package names that don't match the import path ends up being a landmine that trips up a bunch of people. For the visibility question, READMEs in various directories can still be slanted one way or another to steer people to the most relevant thing.
