### ISSUE TITLE
Start New Machine Instances

### ISSUE THREAD

**Issue by ngurajeka** [digitalocean/go-qemu#148]
Hi,

Thanks for the great library. Btw, is there any examples of how to start a new machine? Is starting new machine is the same API with NewDomain? What about image configuration, etc?

Thank you

**Comment by connorkuehl** [comment]
The short answer is no, but if your virtual machine is defined as a libvirt domain, you could use [go-libvirt](https://github.com/digitalocean/go-libvirt) to start it and use go-qemu to communicate directly with it.

There's a deceptive amount of complexity to parameterizing and starting a QEMU VM and we're very grateful to libvirt, virt-install, and virt-manager for managing that complexity for us.
