### ISSUE TITLE
qemu: add additional methods to the Domain type

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/go-qemu#32]
`qemu.Domain` is the type which enables high-level interactions with QEMU.  Adding functionality to it generally requires the following steps:
- issue a `qmp.Cmd` with appropriate parameters
- unmarshal response JSON into anonymous struct
- process anonymous struct into useful data
- return to caller

As an example, see the source for https://godoc.org/github.com/digitalocean/go-qemu#Domain.Version.

Over time, we will ideally be able to implement methods for each supported QMP command from this document: https://github.com/qemu/qemu/blob/master/qmp-commands.hx.

This will be a long-standing issue and additional issues should be created for each new method to be added.  Contributions are very welcome!

**Comment by ndedic** [comment]
Hi @mdlayher, I wanted to give this issue a go but getting the following error when trying to run tests
`
go test  ./...                                                                      
package ./hypervisor                                                                                                   
        imports github.com/digitalocean/go-qemu/internal/shellexec: use of internal package not allowed                
package ./hypervisor                                                                                                   
        imports github.com/digitalocean/go-qemu/internal/virsh: use of internal package not allowed                    
package ./internal/virsh                                                                                               
        imports github.com/digitalocean/go-qemu/internal/shellexec: use of internal package not allowed                
package ./qmp                                                                                                          
        imports github.com/digitalocean/go-qemu/internal/shellexec: use of internal package not allowed                
package ./qmp                                                                                                          
        imports github.com/digitalocean/go-qemu/internal/virsh: use of internal package not allowed  
`

Any clues, should I address this in a separate issue?

**Comment by benlemasurier** [comment]
Hey @ndedic, I'm unable to reproduce this from a fresh clone of the repository. Can you provide any more information about your environment? Any modifications to the source tree? Version of go you're running?

Thanks!

**Comment by ndedic** [comment]
Hi @benlemasurier, I have just cloned the repository again, but got the same result. I am running go1.7 linux/amd64 on Ubuntu 16.04.1 LTS.

**Comment by gliptak** [comment]
@benlemasurier Could you offer the steps you use to build this repo after cloning it? Thanks

**Comment by benlemasurier** [comment]
@gliptak Assuming you're `GOPATH` is properly configured, you can simply:

```go
go get github.com/digitalocean/go-qemu
cd "$GOPATH/src/github.com/digitalocean/go-qemu"
go build
go test -v
```

**Comment by gliptak** [comment]
@benlemasurier Thank you. This does build/test clean with
```
$ go version
go version go1.6.2 linux/amd64
```

**Comment by gliptak** [comment]
Current list of commands seem be at https://github.com/qemu/qemu/blob/master/docs/qmp-commands.txt

There are ~122 commands.

Is there a running list of commands already implemented?

Thanks

**Comment by mdlayher** [comment]
You can check out the godoc page to see what's been implemented. If you have any commands you'd like to see implemented, that would be a great place to start!

**Comment by mdlayher** [comment]
Closing this out.  If you'd like to implement a new function, feel free to file an issue and we'll point you in the right direction with the new developments in code generation and such.
