### ISSUE TITLE
ci: set up matrix builds with different QEMU and libvirt versions for integration testing

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/go-qemu#48]

**Comment by xmudrii** [comment]
Can somebody let me know on which versions of QEMU and libvirt tests need to work?

/cc @benlemasurier @mdlayher

**Comment by benlemasurier** [comment]
Hey @xmudrii,

I think the libvirt versions we currently have provide a good level of coverage. For QEMU, let's go with 2.2, 2.5, and the recent 2.9. The exact versions aren't critical, we're just shooting for general verification.

Thank you!

**Comment by benlemasurier** [comment]
Edit: read this as being part of the [go-libvirt](https://github.com/digitalocean/go-libvirt) project. For libvirt versions, let's go with `1.2.2`, `2.3.0`, `3.1.0`.

**Comment by xmudrii** [comment]
Hi @benlemasurier,

Thank you for answer. Will following combination work?
```
 - QEMU=2.2.0 QEMU_EXT=xz LIBVIRT=1.2.2 LIBVIRT_EXT=gz
 - QEMU=2.5.0 QEMU_EXT=xz LIBVIRT=2.3.0 LIBVIRT_EXT=xz
 - QEMU=2.9.0 QEMU_EXT=xz LIBVIRT=3.1.0 LIBVIRT_EXT=xz
```

If yes, I'll verify are links correct and push update to PR

**Comment by benlemasurier** [comment]
Ideally with a matrix build we'd see a test table more like this:

```
QEMU=2.2.0, LIBVIRT=1.2.2
QEMU=2.2.0, LIBVIRT=2.3.0
QEMU=2.2.0, LIBVIRT=3.1.0
...
QEMU=2.9.0, LIBVIRT=1.2.2
QEMU=2.9.0, LIBVIRT=2.3.0
QEMU=2.9.0, LIBVIRT=3.1.0
```

So, each QEMU version is tested against each libvirt version.

**Comment by xmudrii** [comment]
Okay, I have pushed update to PR :+1:

**Comment by xmudrii** [comment]
Edit: It seems to work, CI is :green_heart:
