### ISSUE TITLE
qemu: simplify testing, remove mockMonitor in tests

### ISSUE THREAD

**Issue by benlemasurier** [digitalocean/go-qemu#70]
`mock_monitor` is too complex, we need to simplify testing. Something like:

```go
func TestBlockStats(t *testing.T) {
    dom := testDomain(t, func(t *testing.T, cmd qmp.Cmd) interface{} {
        if qmp.Cmd != "query-blockstats" // error

        return BlockStats{
            Device: "ide0-0",
        }
    })

    if err := dom.BlockStats(); err != nil {
        //
    }
}
```

**Comment by mdlayher** [comment]
Probably the simplest way to make this work and interoperate with QEMU's JSON format would be to implement `MarshalJSON` and `UnmarshalJSON` on data structures and use those methods to convert between a friendly format and the QEMU format.
