### ISSUE TITLE
*: add example usage binaries

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/go-qemu#78]
Add binaries which demonstrate usage of these packages, and make them easy to build and run to figure out how everything fits together.

**Comment by robertojrojas** [comment]
@mdlayher I would like to help with this issue. Can you clarify what you mean by "binaries"?

**Comment by benlemasurier** [comment]
@mdlayher can probably elaborate but I believe he means example programs i.e., `examples/power_off/main.go`

**Comment by robertojrojas** [comment]
cool beans. I'll start working on some.

**Comment by mdlayher** [comment]
Yep, that's exactly it.  I want to provide some binaries that show how to use these packages.

Another idea is something like `hvls`, which is more or less `virsh list`, and shows all the VMs running on a hypervisor.
